title: OpenZipkin

tagline: A distributed tracing system

description: >
  Zipkin is a distributed tracing system. It helps gather timing data needed to
  troubleshoot latency problems in microservice architectures.

twitter_username: zipkinproject
github_username:  openzipkin

url: https://zipkin.io

defaults:
  -
    values:
      layout: page
      weight: 100   # Used to sort navbar items. Lower weight goes higher on the list.

highlighter: rouge

# This is the best we can get to avoid the unneeded files
exclude: ["zipkin-api/**/*", "zipkin-api/mvnw*", "zipkin-api/*.md", "zipkin-api/*.js*" , "zipkin-api/*.xml"]
include: ["zipkin-api/*.yaml", "zipkin-api/zipkin.proto"]
