#!/bin/sh

set -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.
yamllint -d relaxed _config.yml docker-compose.yml _data/*.yml
bundle exec jekyll build
