version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    steps:
      - checkout
      - run: bundle install
      - run: yaml-lint -i -q .
      - run: bundle exec jekyll build
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/ead3c37d57527214e9f2
    - url: https://webhooks.gitter.im/e/9f1ee2f315d32956f8d6
