version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - run: test -e ./zipkin-api/zipkin2-api.yaml
      - run: gem install bundler --version 2.0.1
      - run: bundle install
      - run: yaml-lint -i -q .
      - run: bundle exec jekyll build
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/ead3c37d57527214e9f2
    - url: https://webhooks.gitter.im/e/e57478303f87ecd7bffc
