#!/bin/sh
#
# Copyright 2014-2020 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

set -ue

# This script ensures bundler is setup and install is run
# Note: these are the last versions of rubygems and bundler to support Ruby 2.7
gem install rubygems-update -v 3.4.22
gem install bundler -v 2.4.22
bundle install
