# yamllint --format github .github/workflows/test.yml
---
name: test

on:
  # We run tests on non-tagged pushes to master
  push:
    tags: ''
    branches: master
    paths-ignore: '**/*.md'
  # We also run tests on pull requests targeted at the master branch.
  pull_request:
    branches: master
    paths-ignore: '**/*.md'

jobs:
  test:
    runs-on: ubuntu-20.04  # newest available distribution, aka focal
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1  # full history is not needed
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          # Match build-bin/configure_test
          rubygems: '3.4.22'
          bundler: '2.4.22'
          bundler-cache: true
      - name: Test
        run: build-bin/test
